name: flutter_widget_from_html_core
version: 0.8.5+3
description: Flutter package to render html as widgets that focuses on correctness and extensibility.
homepage: https://github.com/vtsindia-dev/flutter_widget_from_html_core.git
environment:
  sdk: ">=2.16.0 <=3.0.0"
dependencies:
  csslib: ^0.17.0
  flutter:
    sdk: flutter
  fwfh_text_style: ^2.22.8+1
  html: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.12.0
  lint: any
  mocktail_image_network: ^0.3.0
  test: any
